### ISSUE TITLE
TypeError: argument 2 must be str, not bytes

### ISSUE THREAD

**Issue by brechtm** [thobbs/pure-sasl#21]
Python 3.5 (conda environment), pure-sasl 0.4.0 on RHEL 6.6.

```
Traceback (most recent call last):
  File "/data/data01/dev/edl/infra/mstr/landing/envs/ml_recommender/lib/python3.5/site-packages/impala/sasl_compat.py", line 8, in error_catcher
    yield
  File "/data/data01/dev/edl/infra/mstr/landing/envs/ml_recommender/lib/python3.5/site-packages/impala/sasl_compat.py", line 30, in encode
    return True, self.unwrap(incoming)
  File "/data/data01/dev/edl/infra/mstr/landing/envs/ml_recommender/lib/python3.5/site-packages/puresasl/client.py", line 15, in wrapped
    return f(self, *args, **kwargs)
  File "/data/data01/dev/edl/infra/mstr/landing/envs/ml_recommender/lib/python3.5/site-packages/puresasl/client.py", line 157, in unwrap
    return self._chosen_mech.unwrap(incoming)
  File "/data/data01/dev/edl/infra/mstr/landing/envs/ml_recommender/lib/python3.5/site-packages/puresasl/mechanisms.py", line 515, in unwrap
    kerberos.authGSSClientUnwrap(self.context, incoming)
TypeError: argument 2 must be str, not bytes
```

Using sasl (Cyrus-SASL bindings) instead of pure-sasl, impyla is able to connect.

**Comment by smartie-dieter** [comment]
@brechtm - hey do you already have a solution for your question?
